#!/bin/bash 

dir=$(dirname $0)
cd $dir

source scripts/include_all.sh

# Include aba bin path and common scripts
export PATH=$PWD/bin:$PWD/common/scripts:$PATH

if [ "$1" = "--debug" -o "$1" = "-d" ]; then
	export DEBUG_ABA=1
	set -x
	shift 
fi

## Get the latest stable OCP version number.
stable_ver=$(curl -s https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/release.txt | tee /tmp/.release.txt | \
	 egrep -o "Version: +[0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')
default_ver=$stable_ver

# Extract the previous stable version
stable_ver_point=`expr $(echo $stable_ver | grep ^4 | cut -d\. -f2) - 1`
[ "$stable_ver_point" ] && \
	stable_ver_prev=$(cat /tmp/.release.txt| grep -oE "4\.${stable_ver_point}\.[0-9]+" | tail -n 1)

which openshift-install >/dev/null 2>&1 && cur_ver=$(openshift-install version | grep ^openshift-install | egrep -o "[0-9]+\.[0-9]+\.[0-9]+")

# If openshift-install is already installed, then offer that version also
[ "$cur_ver" ] && or_ret="or hit Return " && default_ver=$cur_ver

target_ver=
while ! echo "$target_ver" | egrep -q "^[0-9]+\.[0-9]+\.[0-9]+" 
do
	[ "$stable_ver" ] && echo "OpenShift latest stable version is $stable_ver (s)" && or_s="or (s) "
	[ "$stable_ver_point" ] && echo "OpenShift latest stable (previous) version is $stable_ver_prev (p)" && or_p="or (p) "
	[ "$cur_ver" ] && echo "The current installed version of 'openshift-install' is $cur_ver (Return)"

	echo    "Which version of OpenShift do you want to install?"
	echo -n "Enter version $or_s$or_p$or_ret [$default_ver]: "

	read target_ver
	[ ! "$target_ver" ] && target_ver=$default_ver
	[ "$target_ver" = "s" ] && target_ver=$stable_ver
	[ "$target_ver" = "p" ] && target_ver=$stable_ver_prev
done

echo "$target_ver" > target-ocp-version.conf

install_rpm podman make jq bind-utils nmstate net-tools skopeo

[ "$target_ver" != "$cur_ver" ] && make -C cli ocp_target_ver=$target_ver all

echo
echo "Now run the following:"
echo "make sync       # ... if you have a 'connected' bastion and want to load the registry directly from the Internet."
echo "make save       # ... if you have a 'disconnected' (or air-gapped) bastion.  See the README file for more information."
echo "make load       # ... if you want to load the registry with the saved images.  See the README file for more information."
echo 
echo After the mirror is working, run one of the following:
echo "make sno"
echo "make compact"
echo "make standard"
echo "make cluster name=mycluster"

