#!/bin/bash -e
# Simple Aba installer.  Copy aba command somewhere into the $PATH

repo=sjbylo/aba
branch=main
[ "$1" = "-q" ] && quiet=1 && shift
[ "$1" ] && repo="$1"
[ "$2" ] && branch="$2"

cd $(dirname $0)

# Only want to use git on the workstation with Internet access
if [ ! -f .bundle ]; then
	if ! which git 2>/dev/null >&2; then
		echo "Please install git and try again!"

		exit 1
	fi
fi

# If we are installing by piping into bash
if ! grep -q "Top level Makefile" Makefile 2>/dev/null; then
	if ! git clone -b $branch https://github.com/${repo}.git; then
		echo "Error fetching git repo from https://github.com/${repo}.git (branch: $branch)" >&2

		exit 1
	fi

	[ ! "$quiet" ] && echo
	[ ! "$quiet" ] && echo "Cloned Aba into $PWD/aba"
	cd aba
fi

if [ -x scripts/aba.sh ]; then
	if [[ "$PATH" =~ "/usr/local/bin:" ]]; then
		[ -s "/usr/local/bin/aba" ] && action="updated to /usr/local/bin" || action="installed to /usr/local/bin"

		if ! sudo cp -p scripts/aba.sh /usr/local/bin/aba; then
			echo "Cannot install $PWD/scripts/aba.sh!  Please copy the script file into your \$PATH." >&2

			exit 1
		fi

	elif [[ "$PATH" =~ "$HOME/bin:" ]]; then
		[ -s "$HOME/bin/aba" ] && action="updated to ~/bin" || action="installed to ~/bin"

		mkdir -p $HOME/bin

		if ! cp -p scripts/aba.sh $HOME/bin/aba; then
			echo "Cannot install $PWD/scripts/aba.sh!  Please copy the script file into your \$PATH." >&2

			exit 1
		fi
	else
		echo "Cannot install $PWD/scripts/aba.sh!  Please copy the script file into your \$PATH." >&2

		exit 1
	fi

	[ ! "$quiet" ] && echo "Aba has been $action"
	[ ! "$quiet" ] && echo "Run: cd aba; aba"
	[ ! "$quiet" ] && echo "Run: cd aba -h for help or see the README.md file"

	exit 0
else
	echo "Abort: Aba script not found in $PWD/scripts/aba.sh" >&2

	exit 1
fi

