# This is the vmware configuration file used by the govc CLI.
# Please go through all values carefully and adjust to your environment!
# See https://github.com/vmware/govmomi/blob/main/govc/README.md#usage for more.

GOVC_URL=vcenter.lan				# vCenter or ESXi host or IP.
GOVC_USERNAME=administrator@vsphere.local	# vCenter or ESXi credentials (ESXi typically uses 'root').
GOVC_PASSWORD='<my password here>'

GOVC_DATASTORE=Datastore			# Datastore for VM disks. Place control-plane VMs on the fastest
						# storage available, e.g. local SSD.
GOVC_NETWORK='VM Network'			# vSphere network for VM connectivity.

#ISO_DATASTORE=Datastore2			# Optional: A boot ISO will be generated for all VMs to boot from.
						# The ISO is uploaded to '[Datastore] /images/agent-<cluster-name>.iso'
						# If the ISO should be stored on a separate datastore, define this here.

GOVC_DATACENTER=Datacenter			# vCenter datacenter name (ESXi: use 'ha-datacenter' or omit).
GOVC_CLUSTER=Cluster				# vCenter compute cluster (ignored for ESXi).
						# Both are also used for vSphere platform integration
						# (StorageClass, MachineSet) when platform=vmw.

VC_FOLDER=/Datacenter/vm			# vCenter folder to hold all clusters (ignored for ESXi).
						# All VMs will be created under VC_FOLDER/<cluster-name>
						# The folder will be created if it does not exist.

GOVC_INSECURE=true				# Disable cert validation.

#GOVC_RESOURCE_POOL='/$GOVC_DATACENTER/host/$GOVC_CLUSTER/Resources'	# Optional: vSphere resource pool for VM placement.

