#!/bin/bash 
# Create a install bundle which can be used to install OCP in an air-gapped env.

source scripts/include_all.sh

aba_debug "Starting: $0 $*"

[ "$1" ] && bundle_dest_file=$1 && shift
[ "$1" ] && force=true && shift
[ "$1" ] && set -x

# This will have been completed behand, but just in case!
install_rpms $(cat templates/rpms-external.txt) || exit 1

source <(normalize-aba-conf)

verify-aba-conf || exit 1

[ ! "$bundle_dest_file" ] && aba_abort "missing install bundle filename! Example: --out /mnt/usb-media/my-bundle"

if [ "$bundle_dest_file" = "-" ]; then
	aba_info "An install bundle will be generated and written to *standard output* (stdout) using the following parameters:" >&2
else
	[ -d $bundle_dest_file ] && bundle_dest_file=$bundle_dest_file/ocp-bundle	# Correct the output location as it needs to be a file
	aba_info "An install bundle file will be generated and saved to disk using the following parameters:" >&2
	bundle_dest_file="$bundle_dest_file-$ocp_version.tar"

	# Sanity write check 
	! echo write test > $bundle_dest_file.tmp && aba_abort "Cannot write to $bundle_dest_file"
	rm -f $bundle_dest_file.tmp
fi

echo >&2
normalize-aba-conf | sed "s/^export //g" | grep -E -o "^(ocp_version|pull_secret_file|ocp_channel)=[^[:space:]]*" >&2
echo Bundle output file = $bundle_dest_file >&2
echo >&2

# User requires to clean out any existing files under mirror/save
if [ "$force" ]; then
	if [ -d mirror/save -a "$(ls mirror/save)" ]; then
		aba_warning "Deleteing all files under aba/mirror/save! (--force set)" >&2
		#echo >&2
		#rm -rf mirror/save/*
		#aba_info Deleting directory $PWD/mirror/save >&2
		rm -rf mirror/save
	fi

	if [ -f $bundle_dest_file ]; then
		aba_warning "Deleting existing bundle file: $bundle_dest_file (--force set)" >&2
		#aba_info Deleting existing bundle file: $bundle_dest_file >&2
		rm -f $bundle_dest_file
	fi
fi

# Check if the repo is alreay in use, e.g. we don't want mirror.conf in the bundle
# "-f, --force" means that "aba bundle" can be run again & again and the image-set config file will be re-created every time
# If these files are generated by aba, then we just ignore them
# Detect if mods have been made
if [ -d mirror/save ]; then
	if [ mirror/save/imageset-config-save.yaml -nt mirror/save/.created ]; then
		# Detect if any image-set archive files exist
		ls mirror/save/mirror_*\.tar >/dev/null 2>&1 && image_set_files_exist=1

		if [ -s mirror/save/imageset-config-save.yaml -o -f mirror/mirror.conf -o "$image_set_files_exist" ]; then
			aba_warning "This repo is already in use!  Modified files exist under: mirror/save"
			echo -n "         " >&2;  ls mirror/save >&2
			[ "$image_set_files_exist" ] && \
			echo_red "         Image set archive file(s) also exist." >&2
			echo_red "         Back up any required files and try again with the '--force' flag to delete all existing files under mirror/save" >&2
			echo_red "         Or, use a fresh Aba repo and try again!" >&2 
			ask "         Files may be overwirtten. Continue anyway" >&2 || exit 1
		fi
	#else
		#aba_warning "Files exist under mirror/save. Back up any required files and try again with the '--force' flag to delete them."  # Note, these files are "owned" still by aba.
	fi
fi

# This is a special case where we want to only send the tar repo contents to stdout 
# so we can do something like: aba bundle ... --out - | ssh host tar xvf - 
if [ "$bundle_dest_file" = "-" ]; then
	#echo "Downloading binary data.  See logfile '.bundle.log' for details." >&2
	echo "Downloading binary data." >&2

	#make -s download save retry=7 2>&1 | cat -v >>.bundle.log
	make -s -C cli download        >&2 	|| exit 1  # Add this here since if there is issue (e.g. op. index failed to d/l) should stop.
	make -s -C mirror save retry=7 >&2 	|| exit 1  # Add this here since if there is issue (e.g. op. index failed to d/l) should stop.

	aba_info "Writing install bundle (tar format) to stdout ..." >&2
	make -s tar out=-   # Be sure the output of this command is ONLY tar output!

	exit
fi

if [ -s $bundle_dest_file ]; then
	aba_warning "File $bundle_dest_file already exists!" 
	ask "The file will be overwirtten. Continue anyway" || exit 1
	##aba_abort "File $bundle_dest_file already exists. Aborting!" 
fi

# Remove unwanted files
aba_info "Deleting unwanted CLI install files under $PWD/cli ..."
ls -1 cli/*tar.gz 2>/dev/null | grep -v -e "-$ocp_version.tar.gz" -e "oc-mirror.*.tar.gz" -e "govc_Linux" | xargs rm -f || true  # ignore any errors
aba_info "Downloading CLI installation files ..."
make -C cli download	# Downlaod required CLIs install files.

if files_on_same_device mirror $bundle_dest_file; then
	echo
	echo_magenta "A *split* install bundle will be created (the bundle will not contain the image-set archive file)."
	echo_magenta "This is because the bundle file and the image-set archive are on the same filesystem."
	echo_magenta "TO GENERATE A *FULL* INSTALL BUNDLE, WRITE IT DIRECTLY TO EXTERNAL MEDIA OR TO A SEPARATE FILESYSTEM."
	ask "Continue anyway" || exit 1
	echo

	aba_info "Pulling images ..."
	make -C mirror save retry=7				# Pull reuqired release (and possibly operator) images.  Retry on failure. 
	aba_info "Creating *split* install bundle archive ..."
	rm -f $bundle_dest_file
	make tarrepo out="$bundle_dest_file"			# Create archive of the repo ONLY, excluding large imageset files.
else
	aba_info "Pulling images ..."
	make -C mirror save retry=7		    		# Pull reuqired release (and possibly operator) images.  Retry on failure.
	aba_info "Creating install bundle archive ..."
	rm -f $bundle_dest_file
	make tar out="$bundle_dest_file"	   		# Create all-in-one archive, including all files. 
fi

exit 0
