#!/bin/bash -e
# Run ONLY the vSphere preflight block (Layers 1-4) against a real vCenter.
# Skips the platform-agnostic checks (DNS, NTP, IP conflicts) that the full
# `make preflight` / `aba install` flow would run first.
#
# This is a diagnostic wrapper - unlike `make preflight`, it prints a
# per-check report (what passed, what failed, what is informational) so you
# can see at a glance whether the configuration is ready for `aba install`.
#
# Usage:
#   cd <cluster-dir>
#   ../scripts/preflight-vsphere.sh
#
# OR from the aba root, passing the cluster dir:
#   scripts/preflight-vsphere.sh <cluster-dir>
#
# Exit code = number of REAL errors reported by preflight_check_vsphere.
# Zero = all hard checks passed.

CLUSTER_DIR="${1:-.}"
if [ ! -d "$CLUSTER_DIR" ]; then
	echo "ERROR: cluster dir '$CLUSTER_DIR' not found" >&2
	exit 2
fi
cd "$CLUSTER_DIR"

if [ ! -f scripts/include_all.sh ]; then
	echo "ERROR: run from a cluster dir (scripts/ symlink not found in '$PWD')" >&2
	echo "       Generate one with: aba cluster -n <name> -t sno --step cluster.conf" >&2
	exit 2
fi

if [ ! -f vmware.conf ]; then
	echo "ERROR: vmware.conf not found in '$PWD'" >&2
	echo "       Copy your working vmware.conf into this cluster dir first." >&2
	exit 2
fi

# Turn on the ABA debug channel so every layer emits its 'ok' / 'resolved'
# aba_debug line into the captured output. The report below greps that
# output to decide per-check status.
export DEBUG_ABA=1

# Disable set -e so individual layer failures don't abort the wrapper
# before we print the report. Counters carry the real status.
set +e

source scripts/include_all.sh

# include_all.sh installs an ERR trap that calls `exit $?` on any non-zero
# command. That is incompatible with the preflight layer design: probes
# return non-zero as a counter-bump signal, NOT as a fatal error. Remove
# the trap so all 4 layers can run to completion and the report can
# summarise every finding.
trap - ERR

source <(normalize-aba-conf)
source <(normalize-cluster-conf)

_preflight_errors=0
_preflight_warnings=0

# Capture the full preflight run. We tee it to stderr so the raw lines stay
# visible during the run (useful if a layer hangs); the report below is
# generated by grepping the captured file afterwards.
_out=$(mktemp)
trap 'rm -f "$_out"' EXIT

source scripts/preflight-check-vsphere.sh
preflight_check_vsphere >"$_out" 2>&1

# --- Report helpers --------------------------------------------------------

# Terminal colours only if stdout is a TTY; plain text otherwise (so logs
# captured to a file stay clean).
if [ -t 1 ]; then
	_C_GREEN=$'\033[32m'
	_C_RED=$'\033[31m'
	_C_YEL=$'\033[33m'
	_C_DIM=$'\033[90m'
	_C_OFF=$'\033[0m'
else
	_C_GREEN=""; _C_RED=""; _C_YEL=""; _C_DIM=""; _C_OFF=""
fi

_row_ok()   { printf "  ${_C_GREEN}[ OK ]${_C_OFF} %-26s %s\n" "$1" "$2"; }
_row_fail() { printf "  ${_C_RED}[FAIL]${_C_OFF} %-26s %s\n" "$1" "$2"; }
_row_info() { printf "  ${_C_YEL}[INFO]${_C_OFF} %-26s %s\n" "$1" "$2"; }
_row_skip() { printf "  ${_C_DIM}[SKIP]${_C_OFF} %-26s %s\n" "$1" "$2"; }

# Probe the captured output for a pattern; echo the first match's captured
# substring (group 1) or the full line.
_first_match() {
	grep -E -m1 -- "$1" "$_out" 2>/dev/null | head -1
}

_has()     { grep -qE -- "$1" "$_out" 2>/dev/null; }
_has_not() { ! grep -qE -- "$1" "$_out" 2>/dev/null; }

# --- Build the report ------------------------------------------------------

echo
echo "=============================================================="
echo " vSphere preflight report"
echo "=============================================================="
echo
echo "Layer 1 - Connectivity"

# TCP
if _has "vSphere: TCP reach to .* ok"; then
	_row_ok   "TCP reachability"      "$(_first_match "TCP reach to [^ ]+" | grep -oE 'TCP reach to [^ ]+' | sed 's/TCP reach to //')"
elif _has "vSphere: cannot reach"; then
	_row_fail "TCP reachability"      "$(_first_match "cannot reach" | sed 's/.*cannot reach //;s/ - .*//')"
else
	_row_skip "TCP reachability"      "(no signal - aborted early?)"
fi

# TLS
if _has "vSphere: skipping TLS check"; then
	_row_skip "TLS trust chain"       "skipped (GOVC_INSECURE=${GOVC_INSECURE:-true})"
elif _has "vSphere: TLS trust chain ok"; then
	_row_ok   "TLS trust chain"       "verified"
elif _has "vSphere: TLS trust chain failure"; then
	_row_fail "TLS trust chain"       "verification failed"
else
	_row_skip "TLS trust chain"       "(not reached)"
fi

# Auth
if _has "vSphere: auth ok"; then
	_row_ok   "Authentication"        "${GOVC_USERNAME:-<unknown user>}"
elif _has "vSphere: authentication to .* failed"; then
	_row_fail "Authentication"        "${GOVC_USERNAME:-<unknown user>} rejected"
else
	_row_skip "Authentication"        "(not reached)"
fi

echo
echo "Layer 2 - Resource existence"

# Datacenter
if _has "vSphere: datacenter '/[^']+' exists"; then
	_row_ok   "Datacenter"            "/$GOVC_DATACENTER"
elif _has "vSphere: datacenter '/[^']+' not found"; then
	_row_fail "Datacenter"            "/$GOVC_DATACENTER (not found)"
else
	_row_skip "Datacenter"            "(not reached)"
fi

# Cluster
if _has "vSphere: cluster '/[^']+' exists"; then
	_row_ok   "Cluster"               "/$GOVC_DATACENTER/host/$GOVC_CLUSTER"
elif _has "vSphere: cluster '/[^']+' not found"; then
	_row_fail "Cluster"               "/$GOVC_DATACENTER/host/$GOVC_CLUSTER (not found)"
else
	_row_skip "Cluster"               "(not reached)"
fi

# Datastore (primary)
if _has "vSphere: datastore '/[^']+' exists"; then
	_row_ok   "Datastore (primary)"   "$GOVC_DATASTORE"
elif _has "vSphere: datastore '/[^']+' not found"; then
	_row_fail "Datastore (primary)"   "$GOVC_DATASTORE (not found)"
else
	_row_skip "Datastore (primary)"   "(not reached)"
fi

# ISO datastore (optional)
if [ -n "${ISO_DATASTORE:-}" ] && [ "$ISO_DATASTORE" != "$GOVC_DATASTORE" ]; then
	iso_line=$(grep -E "vSphere: datastore '/[^']+' (exists|not found)" "$_out" 2>/dev/null | sed -n '2p')
	if echo "$iso_line" | grep -q "exists"; then
		_row_ok   "Datastore (ISO)"       "$ISO_DATASTORE"
	elif echo "$iso_line" | grep -q "not found"; then
		_row_fail "Datastore (ISO)"       "$ISO_DATASTORE (not found)"
	else
		_row_skip "Datastore (ISO)"       "(not reached)"
	fi
fi

# Network - resolved form
if _has "vSphere: network '.*' resolved to '"; then
	resolved=$(_first_match "network '.*' resolved to '[^']+'" | sed -E "s/.*resolved to '([^']+)'.*/\1/")
	_row_ok   "Network"               "$GOVC_NETWORK -> $resolved"
elif _has "vSphere: network '/[^']+' exists"; then
	_row_ok   "Network"               "$GOVC_NETWORK"
elif _has "vSphere: network '/[^']+' not found"; then
	_row_fail "Network"               "$GOVC_NETWORK (not found)"
else
	_row_skip "Network"               "(not reached)"
fi

# Network-on-cluster attachment
if _has "vSphere: network '.*' attached to cluster"; then
	_row_ok   "Network on cluster"    "attached to $GOVC_CLUSTER"
elif _has "vSphere: network '.*' is not attached to any host"; then
	_row_fail "Network on cluster"    "not attached to any host in $GOVC_CLUSTER"
elif _has "vSphere: could not verify network-on-cluster"; then
	_row_info "Network on cluster"    "could not verify (govc read error)"
else
	_row_skip "Network on cluster"    "(not reached)"
fi

# Folder
if _has "vSphere: folder '/[^']+' exists"; then
	_row_ok   "Folder"                "${VC_FOLDER:-}"
elif _has "vSphere: folder '/[^']+' not found"; then
	_row_fail "Folder"                "${VC_FOLDER:-} (not found)"
else
	_row_skip "Folder"                "(not reached)"
fi

# Resource pool
if _has "vSphere: using default resource pool"; then
	_row_ok   "Resource pool"         "(default) /$GOVC_DATACENTER/host/$GOVC_CLUSTER/Resources"
elif _has "vSphere: resource pool '.*' resolved to '"; then
	resolved=$(_first_match "resource pool '.*' resolved to '[^']+'" | sed -E "s/.*resolved to '([^']+)'.*/\1/")
	_row_ok   "Resource pool"         "${GOVC_RESOURCE_POOL:-<default>} -> $resolved"
elif _has "vSphere: resource pool '/[^']+' exists"; then
	_row_ok   "Resource pool"         "${GOVC_RESOURCE_POOL:-<default>}"
elif _has "vSphere: resource pool '.*' not found"; then
	_row_fail "Resource pool"         "${GOVC_RESOURCE_POOL:-<default>} (not found)"
elif _has "vSphere: default resource pool '.*' not found"; then
	_row_fail "Resource pool"         "(default) not found - cluster misconfigured"
else
	_row_skip "Resource pool"         "(not reached)"
fi

echo
echo "Layer 4 - Privileges"

# For each scope check: did it pass, miss privileges, or D-12 group-resolved.
# Count per-scope findings from the captured output.
for scope in root datacenter cluster datastore network folder "resource pool"; do
	scope_label=$(printf "%-16s" "$scope")
	# D-12 group-resolved: no direct role assignment visible
	if grep -qE "^\[ABA\] Warning: vSphere: user '.*' has no role assigned on '/(${GOVC_DATACENTER:-}|$GOVC_DATACENTER/[^']*|)[^']*' " "$_out" && \
	   grep -qE "user '.*' has no role assigned on '.*' \(D-12" "$_out"; then
		# Specific per-scope detection by matching the scope word in context.
		case "$scope" in
			root)         test_path="/" ;;
			datacenter)   test_path="/$GOVC_DATACENTER" ;;
			cluster)      test_path="/$GOVC_DATACENTER/host/$GOVC_CLUSTER" ;;
			datastore)    test_path="$GOVC_DATASTORE" ;;
			network)      test_path="$GOVC_NETWORK" ;;
			folder)       test_path="${VC_FOLDER:-}" ;;
			"resource pool") test_path="${GOVC_RESOURCE_POOL:-}" ;;
		esac
		if grep -qF "has no role assigned on '/' (D-12" "$_out" && [ "$scope" = "root" ]; then
			_row_info "Privilege: root"        "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qF "has no role assigned on '/$GOVC_DATACENTER' (D-12" "$_out" && [ "$scope" = "datacenter" ]; then
			_row_info "Privilege: datacenter"  "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qF "has no role assigned on '/$GOVC_DATACENTER/host/$GOVC_CLUSTER' (D-12" "$_out" && [ "$scope" = "cluster" ]; then
			_row_info "Privilege: cluster"     "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qE "has no role assigned on '/$GOVC_DATACENTER/datastore/.*' \(D-12" "$_out" && [ "$scope" = "datastore" ]; then
			_row_info "Privilege: datastore"   "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qE "has no role assigned on '/$GOVC_DATACENTER/network/.*' \(D-12" "$_out" && [ "$scope" = "network" ]; then
			_row_info "Privilege: network"     "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qE "has no role assigned on '/$GOVC_DATACENTER/vm/.*' \(D-12" "$_out" && [ "$scope" = "folder" ]; then
			_row_info "Privilege: folder"      "group-resolved - cannot pre-verify"
			continue
		fi
		if grep -qE "has no role assigned on '/$GOVC_DATACENTER/host/$GOVC_CLUSTER/Resources.*' \(D-12" "$_out" && [ "$scope" = "resource pool" ]; then
			_row_info "Privilege: resource pool" "group-resolved - cannot pre-verify"
			continue
		fi
	fi

	# If a privilege gap was recorded for this scope, mark it failed.
	if grep -qE "^\[ABA\] Warning: vSphere: $scope '.*' missing privilege" "$_out"; then
		missing_count=$(grep -cE "vSphere: $scope '.*' missing privilege" "$_out")
		_row_fail "Privilege: $scope"          "$missing_count missing privilege(s)"
		continue
	fi

	# No gap, no D-12 for this scope - check passed silently.
	_row_ok   "Privilege: $scope"          "all required privileges present"
done

# --- Summary ---------------------------------------------------------------

d12_count=$(grep -c "D-12; group assignments not resolved" "$_out" 2>/dev/null || true)
real_warnings=$(( _preflight_warnings - d12_count ))
[ "$real_warnings" -lt 0 ] && real_warnings=0

echo
echo "=============================================================="
printf "%-28s %s\n" " Errors (blocking):"           "$_preflight_errors"
printf "%-28s %s\n" " Real warnings:"               "$real_warnings"
printf "%-28s %s\n" " D-12 info (group-resolved):"  "$d12_count"
echo "=============================================================="

if [ "$_preflight_errors" -gt 0 ]; then
	echo "${_C_RED}RESULT: NOT READY${_C_OFF} - fix the [FAIL] rows above before running 'aba install'."
elif [ "$real_warnings" -gt 0 ]; then
	echo "${_C_YEL}RESULT: REVIEW REQUIRED${_C_OFF} - real warnings were reported above."
else
	echo "${_C_GREEN}RESULT: OK${_C_OFF} - all hard checks passed."
	if [ "$d12_count" -gt 0 ]; then
		echo
		echo "About the [INFO] group-resolved privilege rows:"
		echo "  'govc permissions.ls' returns no DIRECT role binding for your user on"
		echo "  those scopes. On enterprise vCenter this almost always means the user"
		echo "  gets its privileges via AD/LDAP group membership, which govc cannot"
		echo "  expand. Preflight cannot pre-verify those - it is a GAP in coverage,"
		echo "  not a failure. If your groups actually grant the privileges listed in"
		echo "  scripts/vmware-required-privileges.sh, 'aba install' will succeed."
	fi
fi

exit "$_preflight_errors"
