#!/bin/bash 
# Either connect to an existing registry or install a fresh one.

# Enable INFO messages by default when called directly from make
# (unless explicitly disabled by parent process via --quiet)
[ -z "${INFO_ABA+x}" ] && export INFO_ABA=1

source scripts/include_all.sh

aba_debug "Starting: $0 $*"

umask 077

source <(normalize-aba-conf)
source <(normalize-mirror-conf)

verify-aba-conf || exit 1
verify-mirror-conf || exit 1

# If we're installing a mirror, then we do need all the "internal" rpms, esp. podman!
scripts/install-rpms.sh internal

export reg_hostport=$reg_host:$reg_port
export reg_url=https://$reg_hostport

# Check if mirror 'registry' credentials exist, e.g. provided by user or auto-generated by mirror installer 
# For existing registry, user must provide the 'regcreds/pull-secret-mirror.json' and the 'regcreds/rootCA.pem' files in regcreds/.
if [ -s regcreds/pull-secret-mirror.json ]; then
	aba_debug "Verifying existing mirror pull secret file: regcreds/pull-secret-mirror.json"

	scripts/reg-verify.sh

	exit
fi

[ ! "$reg_ssh_user" ] && reg_ssh_user=$(whoami)

aba_debug "Verifying resolution of mirror hostname: $reg_host"

# Check the hostname (FDQN) resolves to an IP address, as expected 
# You MUST have a proper DNS entry for OpenShift to install!
fqdn_ip=$(dig +short $reg_host | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}') || true
if [ ! "$fqdn_ip" ]; then
	aba_abort \
		"Hostname: $reg_host does not resolve to an IP address!" \
		"Command used: dig $reg_host +short" \
		"The mirror registry requires a valid DNS record (FQDN)! OpenShift itself also requires two records for API and App ingress!" \
		"Please add/correct your DNS entries or update $PWD/mirror.conf and try again."
fi

# Detect any existing mirror registry?

# Check for Quay...
[ "$http_proxy" ] && echo "$no_proxy" | grep -q "\b$reg_host\b" || no_proxy=$no_proxy,$reg_host		  # adjust if proxy in use
aba_info Probing $reg_url/health/instance

probe_cmd='curl --retry 2 --max-time 10 --connect-timeout 10 -ILsk -o /dev/null -w "%{http_code}\\n" '$reg_url'/health/instance'
aba_debug Probe command: $probe_cmd
reg_code=$(eval $probe_cmd || true)

if [ "$reg_code" = "200" ]; then
	aba_abort \
		"Existing Quay registry found at $reg_url/health/instance" \
		"To use this registry, copy its pull secret file and root CA file into 'aba/mirror/regcreds/' and try again." \
		"The files must be named 'pull-secret-mirror.json' and 'rootCA.pem' respectively." \
		"The pull secret file can also be created and verified using 'aba -d mirror password'" \
		"if you don't recognize: $reg_url, be sure to edit the file: $PWD/mirror.conf!" \
		"See the README.md for further information." 
fi

# Check for any endpoint ...
aba_info Probing $reg_url/

probe_cmd='curl --retry 2 --max-time 10 --connect-timeout 10 -ILsk -o /dev/null -w "%{http_code}\\n" '$reg_url'/'
aba_debug Probe command: $probe_cmd
reg_code=$(eval $probe_cmd || true)

if [ "$reg_code" = "200" ]; then
	aba_abort \
		"Endpoint found at $reg_url/" \
		"If this is your existing registry, copy its pull secret file and root CA file into 'aba/mirror/regcreds/' and try again." \
		"The files must be named 'pull-secret-mirror.json' and 'rootCA.pem' respectively." \
		"The pull secret file can also be created and verified using 'aba -d mirror password'" \
		"if you don't recognize: $reg_url, be sure to edit the file: $PWD/mirror.conf!" \
		"See the README.md for further information."
fi

[ ! "$data_dir" ] && data_dir=\~
reg_root=$data_dir/quay-install

if [[ "$reg_root" != /* && "$reg_root" != ~* ]]; then
	aba_abort \
		"The value: data_dir must be an 'absolute path', i.e. starting with a '/' or a '~' char! Fix this in $PWD/mirror.conf and try again!" 
fi

mkdir -p ~/.aba
ssh_conf_file=~/.aba/ssh.conf

# Now added in ./install script
#cat > $ssh_conf_file <<END
#StrictHostKeyChecking no
#UserKnownHostsFile=/dev/null
#ConnectTimeout=15
#PreferredAuthentications=publickey
#PasswordAuthentication=no
#LogLevel=ERROR
#END

flag_file=/tmp/.$(whoami).$RANDOM
rm -f $flag_file

# Install Quay mirror on **remote host** if ssh key defined 
if [ "$reg_ssh_key" ]; then
	aba_debug "Starting to install Quay to remote host"

	# First, ensure the reg host points to a remote host and not this localhost
	aba_info "The Quay mirror registry is configured to be installed on a *remote* host (since 'reg_ssh_key' *is defined* in 'mirror/mirror.conf')."
	aba_info "Verifying FQDN '$reg_host' points to a remote host ..."

	# try to create a random file on the host and check the file does not exist on this localhost 
	if ! ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host touch $flag_file; then
		aba_abort \
			"Can't ssh to '$reg_ssh_user@$reg_host' using key '$reg_ssh_key'" \
			"Tested with command: ssh -i $reg_ssh_key $reg_ssh_user@$reg_host" \
			"Ensure password-less ssh to the remote host '$reg_ssh_user@$reg_host' is working and try again." \
			"Or, you might need to set 'reg_ssh_user' in mirror.conf?" 
	fi

	# If the flag file exists on localhost, then the FQDN points to this host (mirror.conf wrong!) 
	if [ -f $flag_file ]; then
		rm -f $flag_file

		# FIXME: The following would be to continue with local host installation...
		# CONT # echo_red "The mirror registry is configured to be installed on a *remote* host." 
		# CONT # echo_red "But $reg_host ($fqdn_ip) reaches this localhost ($(hostname -s)) instead!" 
		# CONT # echo_red "Quay will be installed on this localhost unless you properly set reg_ssh_key in aba/mirror/mirror.conf" 
		# CONT # echo_red "IGNORING value reg_ssh_key for now so Quay will be installed on localhost!"
		# CONT # reg_ssh_key=

		aba_abort \
			"The mirror registry is configured to be installed on a *remote* host." \
			"But $reg_host ($fqdn_ip) reaches this localhost ($(hostname -s)) instead!" \
			"You have two options:" \
			"1. If Quay should be installed on localhost ($(hostname -s)), undefine 'reg_ssh_key' in 'aba/mirror/mirror.conf'." \
			"2. If '$reg_host' should refer to a remote host, update the DNS record ($reg_host) to" \
			"resolve to an IP that can be used to reach the *remote* host via ssh." \
			"Correct the problem, either in 'aba/mirror/mirror.conf' or in the DNS, and try again." 
	fi
# CONT # fi

# CONT # if [ "$reg_ssh_key" ]; then
	ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host rm -f $flag_file

	aba_info "Ssh access to remote host ($reg_ssh_user@$reg_host using key $reg_ssh_key) is working ..."

	ask "Install Quay mirror registry on remote host ($reg_ssh_user@$reg_host:$reg_root), accessable via $reg_hostport" || exit 1

	aba_info "Installing Quay registry to remote host at $reg_ssh_user@$reg_host ..."

	aba_info "Running checks on remote host: $reg_host.  See $PWD/.remote_host_check.out file for output."

	> .remote_host_check.out
	err=
	ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host "set -x; ip a" >> .remote_host_check.out 2>&1
	ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host "set -x; rpm -q podman || $SUDO dnf install podman jq -y" >> .remote_host_check.out 2>&1 || err=1
	ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host "set -x; rpm -q jq 	|| $SUDO dnf install podman jq -y" >> .remote_host_check.out 2>&1 || err=1
	ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host "set -x; podman images" >> .remote_host_check.out 2>&1 || err=1

	[ "$err" ] && aba_abort "Install 'podman' and 'jq' on the remote host '$reg_host' and try again."

	# Note that the mirror-registry installer does not open the port for us
	if ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host -- "rpm -q firewalld >/dev/null"; then
		aba_info "Allowing firewall access to the registry at $reg_host/$reg_port ..."

		if ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host -- "systemctl is-active firewalld >/dev/null"; then
			ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host -- "$SUDO firewall-cmd --state >/dev/null && \
				$SUDO firewall-cmd --add-port=$reg_port/tcp --permanent >/dev/null && \
					$SUDO firewall-cmd --reload >/dev/null"
		else
			ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host -- "$SUDO firewall-offline-cmd --add-port=$reg_port/tcp >/dev/null"
		fi
	fi

	# Fetch the actual absolute dir path for $reg_root.  "~" on remote host may be diff. to this localhost. Ansible installer does not eval "~"
	reg_root=$(ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host echo $reg_root)

	reg_root_opts="--quayRoot $reg_root --quayStorage $reg_root/quay-storage --sqliteStorage $reg_root/sqlite-storage"

	aba_info "Using registry root dir: $reg_root and options: $reg_root_opts"

	aba_info "Installing mirror registry on the remote host [$reg_host] with user $reg_ssh_user into dir $reg_root ..."

	if [ ! "$reg_pw" ]; then
		# Generate random password 
		reg_pw=$(openssl rand -base64 12)
	fi

	# Note: The quay installer seems to ONLY create an ssh key if it needs one for the localhost.  It uses the provided key for remote hosts.
	# The following is not required for remote host install.
	# This is a workaround to ensure a more secure key for Quay, otherwise smaller key sizes can be rejected by policy
	#[ ! -s $HOME/.ssh/quay_installer ] && \
	#	ssh-keygen -t ed25519 -f $HOME/.ssh/quay_installer -N '' >/dev/null && \
	#	cat $HOME/.ssh/quay_installer.pub >> $HOME/.ssh/authorized_keys

	# Generate the script to be used to delete this registry
	uninstall_cmd="eval ./mirror-registry uninstall --targetUsername $reg_ssh_user --targetHostname $reg_host -k $reg_ssh_key $reg_root_opts --autoApprove -v"

	echo "reg_delete() { echo [ABA] Running command: \"$uninstall_cmd\"; $uninstall_cmd;}" > ./reg-uninstall.sh
	echo reg_host_to_del=$reg_host >> ./reg-uninstall.sh
	aba_info "Created Quay uninstall script at $PWD/reg-uninstall.sh"

	cmd="./mirror-registry install -v --initUser $reg_user --quayHostname $reg_host --targetUsername $reg_ssh_user --targetHostname $reg_host -k $reg_ssh_key $reg_root_opts"

	aba_info "Installing mirror registry with command:"
	aba_info "$cmd --initPassword <hidden>"

	if ! ensure_mirror_registry; then
		error_msg=$(get_task_error "$TASK_MIRROR_REG")
		aba_abort "Failed to download mirror-install:\n$error_msg\n\nPlease check network and try again."
	fi

	eval echo $cmd --initPassword "'$reg_pw'"
	eval $cmd --initPassword "'$reg_pw'"

	if [ -d regcreds ]; then
		rm -rf regcreds.bk
		mv regcreds regcreds.bk
	fi

	mkdir regcreds

	# Fetch root CA from remote host 
	aba_info "Fetching root CA from remote host: $reg_ssh_user@$reg_host:$reg_root/quay-rootCA/rootCA.pem"
	scp -i $reg_ssh_key -F $ssh_conf_file -p $reg_ssh_user@$reg_host:$reg_root/quay-rootCA/rootCA.pem regcreds/

	[ ! "$reg_user" ] && reg_user=init

	# Check if the cert needs to be updated
	trust_root_ca regcreds/rootCA.pem

	# FIXME: Not really needed
	#[ ! "$tls_verify" ] && tls_verify_opts="--tls-verify=false"

	# Configure the pull secret for this mirror registry 
	aba_info "Generating regcreds/pull-secret-mirror.json file"
	export enc_password=$(echo -n "$reg_user:$reg_pw" | base64 -w0)
	# Inputs: enc_password, reg_host and reg_port 
	scripts/j2 ./templates/pull-secret-mirror.json.j2 > ./regcreds/pull-secret-mirror.json

	### use verify ### podman logout --all >/dev/null 
	### use verify ### echo -n "Checking registry access is working using 'podman login' ... "
	### use verify ### echo "Running: podman login -u $reg_user -p $reg_pw $reg_url"
	### use verify ### # FIXME: tls_verify_opts not used
	### use verify ### #podman login $tls_verify_opts -u $reg_user -p $reg_pw $reg_url 
	### use verify ### podman login $tls_verify_opts -u $reg_user -p $reg_pw $reg_url 

	echo Registry installed from $(hostname):$PWD | \
		ssh -i $reg_ssh_key -F $ssh_conf_file $reg_ssh_user@$reg_host -- "cat > $reg_root/.install.source"
else
	aba_debug "Starting to install Quay to local host"

	# First, ensure the reg host points to this localhost and not a remote host
	# Sanity check to see if the correct host was defined
	# Resolve FQDN
	aba_info "The Quay mirror is configured to be installed on *localhost* (since 'reg_ssh_key' *is not defined* in 'aba/mirror/mirror.conf')."
	aba_info "Verifying FQDN '$reg_host' (IP: $fqdn_ip) allows access to this localhost ..."

	# Get local IP addresses
	local_ips=$(hostname -I)

	# For local install, check if FQDN IP DOES NOT match any local IPs
	# We will leave this only as a warning, not an error since sometimes there is a NAT in use which is difficult to check
	if ! echo "$local_ips" | grep -qw "$fqdn_ip"; then
		aba_warning \
			"$reg_host resolves to $fqdn_ip which is not configured or found on any local network interfaces." \
			"Ignore this warning if this behavior is expected, for example, when $fqdn_ip refers to an external IP address." 

		sleep 1
		##exit 1  # We will leave this only as a warning, not an error since sometimes there is a NAT/LB (ip is external) in use which is difficult to check
	fi

	# On the off-chance that ssh does work out-of-the-box to this host using the default key, let's check $reg_host is NOT a remote host!
	# It's expected that this may fail since there may not be any default ssh key configured. But, if it is and ssh reaches a remote host, then we
	# can catch that early here and show a warning. 
	if h=$(ssh -F $ssh_conf_file                  $reg_host touch $flag_file; hostname) >/dev/null 2>&1; then
		if [ ! -f $flag_file ]; then

			aba_warning \
				"The mirror registry is configured in 'aba/mirror/mirror.conf' to be installed *locally* (reg_ssh_key *is not* defined)." \
				"But $reg_host resolves to $fqdn_ip, which reaches a remote host [$h] via ssh!" \
				"You have two options:" \
				"1. If '$reg_host' should refer to this *localhost*, update its DNS record to resolve to an IP address that correctly reaches this localhost '$(hostname -s)'." \
				"2. If the above behavior is correct and you intend to install Quay on a remote host, set 'reg_ssh_key' in 'aba/mirror/mirror.conf'." \
				"Correct the problem, either in 'aba/mirror/mirror.conf' or in the DNS, and try again." 

			sleep 2
		else
			rm -f $flag_file
			aba_info "Ssh access to localhost via '$reg_host' is working."  # Completing the 'Verifying...' message above
		fi
	fi
	# ssh to localhost is required by the Quay installer to install on localhost
	# Check ssh to localhost, but show only a warning since this is hard to verify.
	temp_aba_key=~/.ssh/aba_check_ssh
	temp_aba_pub_key=~/.ssh/aba_check_ssh.pub
	if [ ! -s $temp_aba_key ]; then
		if [ ! -w ~/.ssh ]; then
			aba_warning "Cannot write to ~/.ssh to check ssh connectivity! For a local installation of Quay, the installer will likely fail." 

			sleep 2
		else
			aba_debug "Creating test ssh key: $temp_aba_key" 
			# Create key for testing ssh
			ssh-keygen -t rsa -f $temp_aba_key -N '' >/dev/null 
			chmod 600 $temp_aba_key $temp_aba_pub_key
			cat $temp_aba_pub_key >> ~/.ssh/authorized_keys
			# Note: do not delete the test key after testing, since it was added it to the authorized_keys file
		fi
	fi

	if [ -s $temp_aba_key ]; then
		# Try to ssh to *localhost* since the installer will do the same.
		if ! ssh -F $ssh_conf_file -i $temp_aba_key $reg_host touch $flag_file >/dev/null     ; then
			# This must work for the Quay installer
			aba_abort \
				"For a local installation of Quay, ssh must allow access to this host via the FQDN $reg_host. The Quay installer requires this." \
				"Failed command: ssh -i $temp_aba_key $reg_host" 
		fi
	fi

	ask "Install Quay mirror registry appliance to localhost ($(hostname -s)), accessable via $reg_hostport" || exit 1
	aba_info "Installing Quay registry on localhost ..."

	# mirror-registry installer does not open the port for us
	if rpm -q firewalld >/dev/null; then
		aba_info "Allowing firewall access to this host at $reg_host/$reg_port ..."

		if systemctl is-active firewalld >/dev/null; then
			$SUDO firewall-cmd --state && \
				$SUDO firewall-cmd --add-port=$reg_port/tcp --permanent && \
					$SUDO firewall-cmd --reload
		else
			$SUDO firewall-offline-cmd --add-port=$reg_port/tcp >/dev/null
		fi
	fi

	# Create random password
	if [ ! "$reg_pw" ]; then
		reg_pw=$(openssl rand -base64 12)
	fi

	if [ "$reg_root" ]; then
		reg_root_opts="--quayRoot $reg_root --quayStorage $reg_root/quay-storage --sqliteStorage $reg_root/sqlite-storage"
		aba_info "Using registry root dir: $reg_root and options: $reg_root_opts"
	else
		aba_info "Using registry root dir: $reg_root"
	fi

	# Generate the script to be used to delete this registry
	uninstall_cmd="eval ./mirror-registry uninstall --autoApprove $reg_root_opts -v"
	echo "reg_delete() { echo [ABA] Running command: \"$uninstall_cmd\"; $uninstall_cmd;}" > ./reg-uninstall.sh
	echo reg_host_to_del=$reg_host >> ./reg-uninstall.sh
	aba_info "Created Quay uninstall script at $PWD/reg-uninstall.sh"

	# This is a workaround to ensure a more secure key for Quay, otherwise smaller key sizes can be rejected by policy
	#[ ! -s $HOME/.ssh/quay_installer ] && ssh-keygen -t rsa -b 3072 -f $HOME/.ssh/quay_installer -N '' >/dev/null 
	[ ! -s $HOME/.ssh/quay_installer ] && \
		ssh-keygen -t ed25519 -f $HOME/.ssh/quay_installer -N '' >/dev/null && \
		cat $HOME/.ssh/quay_installer.pub >> $HOME/.ssh/authorized_keys

	cmd="./mirror-registry install -v --initUser $reg_user --quayHostname $reg_host $reg_root_opts"

	aba_info "Installing mirror registry with command:"
	aba_info "$cmd --initPassword <hidden>"

	if ! ensure_mirror_registry; then
		error_msg=$(get_task_error "$TASK_MIRROR_REG")
		aba_abort "Failed to download mirror-install:\n$error_msg\n\nPlease check network and try again."
	fi

	eval $cmd --initPassword $reg_pw   # eval needed for "~"

	if [ -d regcreds ]; then
		rm -rf regcreds.bk
		mv regcreds regcreds.bk
	fi
	mkdir regcreds

	# Fetch root CA from localhost 
	eval cp $reg_root/quay-rootCA/rootCA.pem regcreds/   # eval since $reg_root may container "~"

	[ ! "$reg_user" ] && reg_user=init

	# Check if the cert needs to be updated
	trust_root_ca regcreds/rootCA.pem

	#[ ! "$tls_verify" ] && tls_verify_opts="--tls-verify=false"

	### use verify ### podman logout --all >/dev/null 
	### use verify ### echo -n "Checking registry access is working using 'podman login' ... "
	### use verify ### #echo "Running: podman login $tls_verify_opts -u $reg_user -p $reg_pw $reg_url"
	### use verify ### echo "Running: podman login -u $reg_user -p $reg_pw $reg_url"
	### use verify ### # FIXME: tls_verify_opts not used
	### use verify ### #podman login $tls_verify_opts -u $reg_user -p $reg_pw $reg_url 
	### use verify ### podman login $tls_verify_opts -u $reg_user -p $reg_pw $reg_url 

	aba_info "Generating regcreds/pull-secret-mirror.json file"
	export enc_password=$(echo -n "$reg_user:$reg_pw" | base64 -w0)

	# Inputs: enc_password, reg_host and reg_port 
	scripts/j2 ./templates/pull-secret-mirror.json.j2 > ./regcreds/pull-secret-mirror.json

	#touch $reg_root/registry-installed-from$(pwd | tr / -)
	eval "echo Registry installed from $(hostname -f):$PWD > $reg_root/.install.source"
fi

echo
aba_info_ok "Registry installated/configured successfully!"
